### ISSUE TITLE
Can't see storm metrics in graphite UI

### ISSUE THREAD

**Issue by alecinvan** [verisign/storm-graphite#6]
Hi, 
I was able to successfully build the jars, here is what I did to be able to monitor storm topology in graphite web UI. My storm cluster is 3-node cluster, and I get graphite installed on one of nodes.

1.  I copy these jar files into $storm_home/lib of each node, which is /etc/storm/lib

```
-rw-r--r--  1 stuser storm   146358 Mar 11 16:57 storm-graphite-0.1.5-SNAPSHOT-all.jar
-rw-r--r--  1 stuser storm     8214 Mar 11 16:57 storm-graphite-0.1.5-SNAPSHOT.jar
-rw-r--r--  1 stuser storm    48800 Mar 11 16:57 storm-graphite-0.1.5-SNAPSHOT-javadoc.jar
-rw-r--r--  1 stuser storm     7275 Mar 11 16:57 storm-graphite-0.1.5-SNAPSHOT-sources.jar
```

2. In storm.yaml of each node, I add such

```
topology.builtin.metrics.bucket.size.secs: 10
topology.metrics.consumer.register:
  - class: "com.verisign.storm.metrics.GraphiteMetricsConsumer"
    parallelism.hint: 1
    argument:
      metrics.graphite.host: "10.100.70.29"
      metrics.graphite.port: "2003"
      metrics.graphite.prefix: "storm.devCluster.metrics"
      metrics.graphite.min-connect-attempt-interval-secs: "5"
```

And restart each node storm-supervisor. 

3, Config storage-schemas.conf

```
[carbon]
pattern = ^carbon\.
retentions = 1min:180d,10min:180d

[storm_metrics]
pattern = ^storm\.devCluster\.metrics\.
retentions = 10s:2d,1m:30d,5m:90d,1h:2y

[default_1min_for_1day]
pattern = .*
retentions = 60s:1d
```

4. set carbon-cache and carbon-aggregator in terms of 
http://www.michael-noll.com/blog/2013/11/06/sending-metrics-from-storm-to-graphite/
But I did have whisper up as well.

After done all of above, I am running my topos, but I was unable to see any storm buildin metric in graphite web UI. Did I miss something?

thanks
AL
